#!/bin/sh
set -e

DKMS_NAME=matrixio-kernel-modules
DKMS_PACKAGE_NAME=$DKMS_NAME-dkms
DKMS_VERSION=0.2.4

postinst_found=0

case "$1" in
	configure)
		for DKMS_POSTINST in /usr/lib/dkms/common.postinst /usr/share/$DKMS_PACKAGE_NAME/postinst; do
			if [ -f $DKMS_POSTINST ]; then
				$DKMS_POSTINST $DKMS_NAME $DKMS_VERSION /usr/share/$DKMS_PACKAGE_NAME "" $2
				postinst_found=1
				break
			fi
		done
		if [ "$postinst_found" -eq 0 ]; then
			echo "ERROR: DKMS version is too old and $DKMS_PACKAGE_NAME was not"
			echo "built with legacy DKMS support."
			echo "You must either rebuild $DKMS_PACKAGE_NAME with legacy postinst"
			echo "support or upgrade DKMS to a more current version."
			exit 1
		else
			echo "Enable configurations in /boot/config.txt"
			cp /boot/config.txt /boot/config.txt.matrixio.bk \
			&& /usr/share/matrixlabs/matrixio-devices/matrixlabs_edit_settings.py \
			  /boot/config.txt.matrixio.bk \
		   	  /usr/share/matrixlabs/matrixio-devices/config/kernel_modifications.txt > /boot/config.txt 
		fi
	;;
esac

